version: '3.2'

networks:
  dockerapi-dev:
    driver: bridge 
 
services:
  postgres_image:
    image: postgres:latest
    ports:
      - published: 5900
        target: 5432
    restart: 
        always
    environment:
      POSTGRES_USER: "docker"
      POSTGRES_PASSWORD: "docker"
      POSTGRES_DB: "docker"
    networks:
      - dockerapi-dev 
  data_microservice:
    image: dawidnowicki/clothes_data_microservice
    ports:
      - published: 44201
        target: 80
    networks:
      - dockerapi-dev
    environment:
        DATABASE_PATH: "host=postgres_image;port=5432;database=docker;username=docker;password=docker"
    depends_on:
       - postgres_image
  application_microservice:
    image: dawidnowicki/clothes_application_microservice
    ports:
      - published: 44202
        target: 80
    networks:
      - dockerapi-dev
    environment:
# token from https://openweathermap.org/api
        - SECRET_WEATHER_API=
        - CLOTHES_DATA_API=data_microservice
        - CLOTHES_DATA_API_PORT=80
    depends_on:
      - postgres_image
      - data_microservice
  client:
    image: dawidnowicki/clothes_client_microservice
    ports:
      - published: 80
        target: 80
    networks:
      - dockerapi-dev
    environment:
        API_URL:application_microservice:80/
    depends_on:
        - postgres_image
        - data_microservice
        - application_microservice
volumes: 
  db_volume:
